// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDduJgcAW3pu1lLmiNC0nweWeCaM55uWSM',
    appId: '1:774745554312:web:f20069686f1e76f99bce3d',
    messagingSenderId: '774745554312',
    projectId: 'book-booster',
    authDomain: 'book-booster.firebaseapp.com',
    storageBucket: 'book-booster.appspot.com',
    measurementId: 'G-21TFV681DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrvRLEM5io7xK5RC5K42waU8IO1lmbPrU',
    appId: '1:774745554312:android:a2c94a1cfb4531e29bce3d',
    messagingSenderId: '774745554312',
    projectId: 'book-booster',
    storageBucket: 'book-booster.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtjUM1AXxTSKilBdUQ0XdVIq5Mdw98Elk',
    appId: '1:774745554312:ios:31e74f9a2436a76f9bce3d',
    messagingSenderId: '774745554312',
    projectId: 'book-booster',
    storageBucket: 'book-booster.appspot.com',
    iosBundleId: 'com.example.bookBooster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtjUM1AXxTSKilBdUQ0XdVIq5Mdw98Elk',
    appId: '1:774745554312:ios:d13821c4530ba1299bce3d',
    messagingSenderId: '774745554312',
    projectId: 'book-booster',
    storageBucket: 'book-booster.appspot.com',
    iosBundleId: 'com.example.bookBooster.RunnerTests',
  );
}
