name: book_booster
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  cloud_firestore: ^4.11.0
  dio: ^5.3.3
  firebase_auth: ^4.12.0
  firebase_core: ^2.18.0
  firebase_storage: ^11.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.6.0
  path_provider: ^2.1.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/stocks/
    - assets/images/fiction/
